# -*- mode: ruby -*-
# vi: set ft=ruby :
#CrowdHoster Vagrant Configuration File
Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 5000, host: 5050
  config.vm.provision :shell, :path => "https://raw2.github.com/rmostafa/Crowdhoster/master/railsScript.sh"
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--memory", "2500"]
end
end